### PR TITLE
🐛 Fix function colours producing false positive results

### LINKED ISSUE #3: False positives with `rgb`, `rgba`, `hsl` and `hsla` values
Firstly, thanks for this module. I was about to write my own colour validation for https://placeholders.dev before stumbling across this. 👍

However, it seems that there are some false positives with RGB, etc. values:

```js
validateColor('rgba(255,255,255,1)'); // true
validateColor('rgba(255,255,255,1)dsadasda'); // true
```

This can also be replicated for `rgb`, `hsl` and `hsla` values.

### PR DESCRIPTION
**Pull request by Cherry**
This resolves #3 . I also added a few tests to ensure no regression can happen in the future. 👍

Let me know if you'd like any further changes.

### CODE REVIEW

**Comment by dreamyguy** [comment]
Amazing what one character too much can lead to. Cheers for the tests! I'll be tagging and pushing a new release soon! Thanks!! 🚀 ✨

**Comment by Cherry** [comment]
@dreamyguy Any news on a new release? I'd love to update things on my end.

**Comment by dreamyguy** [comment]
@Cherry I'm sorry for not coming back sooner, my sister passed away and I left everything slide for a while... I did a release on April 5, but forgot to give you a heads up.

These are the changes https://github.com/dreamyguy/validate-color/compare/v1.0.6...v1.0.7

**Comment by Cherry** [comment]
@dreamyguy I'm so sorry for your loss. I hope things get better for you soon.

There's absolutely no rush on this and I can keep you using v1.0.6 for now, but when you do have a moment, if you can check into https://github.com/dreamyguy/validate-color/issues/7, I'd really appreciate it.

**Pull request merged**
