### PR TITLE
🎉 Add TypeScript typings

### PR DESCRIPTION
**Pull request by LinusU**
I've tried these in my own project and they work great 💪 

This is awesome even for people not using TypeScript, since they show up in VS Code and other code editors 😎

### CODE REVIEW

**Comment by LinusU** [comment]
ping @dreamyguy

**Comment by dreamyguy** [comment]
Cheers @LinusU! 🎉

**Comment by LinusU** [comment]
Thanks for the merge!

Would appreciate it if you could cut a release as well, we currently need to add this as a git dependency. Thanks! ☺️

**Comment by dreamyguy** [comment]
Done! Sorry for the delay, life happened...

**Pull request merged**
